// source: processed.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.LaneChangesForVideo');
goog.provide('proto.api.LaneChangesForVideo.LaneChangeForFrame');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.LaneChangesForVideo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.LaneChangesForVideo.repeatedFields_, null);
};
goog.inherits(proto.api.LaneChangesForVideo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.LaneChangesForVideo.displayName = 'proto.api.LaneChangesForVideo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.LaneChangesForVideo.LaneChangeForFrame = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.LaneChangesForVideo.LaneChangeForFrame, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.LaneChangesForVideo.LaneChangeForFrame.displayName = 'proto.api.LaneChangesForVideo.LaneChangeForFrame';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.LaneChangesForVideo.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.LaneChangesForVideo.prototype.toObject = function(opt_includeInstance) {
  return proto.api.LaneChangesForVideo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.LaneChangesForVideo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.LaneChangesForVideo.toObject = function(includeInstance, msg) {
  var f, obj = {
    numFrames: jspb.Message.getFieldWithDefault(msg, 1, 0),
    laneChangeForFrameList: jspb.Message.toObjectList(msg.getLaneChangeForFrameList(),
    proto.api.LaneChangesForVideo.LaneChangeForFrame.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.LaneChangesForVideo}
 */
proto.api.LaneChangesForVideo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.LaneChangesForVideo;
  return proto.api.LaneChangesForVideo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.LaneChangesForVideo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.LaneChangesForVideo}
 */
proto.api.LaneChangesForVideo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumFrames(value);
      break;
    case 2:
      var value = new proto.api.LaneChangesForVideo.LaneChangeForFrame;
      reader.readMessage(value,proto.api.LaneChangesForVideo.LaneChangeForFrame.deserializeBinaryFromReader);
      msg.addLaneChangeForFrame(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.LaneChangesForVideo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.LaneChangesForVideo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.LaneChangesForVideo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.LaneChangesForVideo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumFrames();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getLaneChangeForFrameList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.api.LaneChangesForVideo.LaneChangeForFrame.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.LaneChangesForVideo.LaneChangeForFrame.prototype.toObject = function(opt_includeInstance) {
  return proto.api.LaneChangesForVideo.LaneChangeForFrame.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.LaneChangesForVideo.LaneChangeForFrame} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.LaneChangesForVideo.LaneChangeForFrame.toObject = function(includeInstance, msg) {
  var f, obj = {
    frameIndex: jspb.Message.getFieldWithDefault(msg, 1, 0),
    laneChange: jspb.Message.getBooleanFieldWithDefault(msg, 101, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.LaneChangesForVideo.LaneChangeForFrame}
 */
proto.api.LaneChangesForVideo.LaneChangeForFrame.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.LaneChangesForVideo.LaneChangeForFrame;
  return proto.api.LaneChangesForVideo.LaneChangeForFrame.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.LaneChangesForVideo.LaneChangeForFrame} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.LaneChangesForVideo.LaneChangeForFrame}
 */
proto.api.LaneChangesForVideo.LaneChangeForFrame.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFrameIndex(value);
      break;
    case 101:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLaneChange(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.LaneChangesForVideo.LaneChangeForFrame.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.LaneChangesForVideo.LaneChangeForFrame.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.LaneChangesForVideo.LaneChangeForFrame} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.LaneChangesForVideo.LaneChangeForFrame.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFrameIndex();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getLaneChange();
  if (f) {
    writer.writeBool(
      101,
      f
    );
  }
};


/**
 * optional int64 frame_index = 1;
 * @return {number}
 */
proto.api.LaneChangesForVideo.LaneChangeForFrame.prototype.getFrameIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.LaneChangesForVideo.LaneChangeForFrame} returns this
 */
proto.api.LaneChangesForVideo.LaneChangeForFrame.prototype.setFrameIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool lane_change = 101;
 * @return {boolean}
 */
proto.api.LaneChangesForVideo.LaneChangeForFrame.prototype.getLaneChange = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 101, false));
};


/**
 * @param {boolean} value
 * @return {!proto.api.LaneChangesForVideo.LaneChangeForFrame} returns this
 */
proto.api.LaneChangesForVideo.LaneChangeForFrame.prototype.setLaneChange = function(value) {
  return jspb.Message.setProto3BooleanField(this, 101, value);
};


/**
 * optional int64 num_frames = 1;
 * @return {number}
 */
proto.api.LaneChangesForVideo.prototype.getNumFrames = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.LaneChangesForVideo} returns this
 */
proto.api.LaneChangesForVideo.prototype.setNumFrames = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated LaneChangeForFrame lane_change_for_frame = 2;
 * @return {!Array<!proto.api.LaneChangesForVideo.LaneChangeForFrame>}
 */
proto.api.LaneChangesForVideo.prototype.getLaneChangeForFrameList = function() {
  return /** @type{!Array<!proto.api.LaneChangesForVideo.LaneChangeForFrame>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.LaneChangesForVideo.LaneChangeForFrame, 2));
};


/**
 * @param {!Array<!proto.api.LaneChangesForVideo.LaneChangeForFrame>} value
 * @return {!proto.api.LaneChangesForVideo} returns this
*/
proto.api.LaneChangesForVideo.prototype.setLaneChangeForFrameList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.api.LaneChangesForVideo.LaneChangeForFrame=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.LaneChangesForVideo.LaneChangeForFrame}
 */
proto.api.LaneChangesForVideo.prototype.addLaneChangeForFrame = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.api.LaneChangesForVideo.LaneChangeForFrame, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.LaneChangesForVideo} returns this
 */
proto.api.LaneChangesForVideo.prototype.clearLaneChangeForFrameList = function() {
  return this.setLaneChangeForFrameList([]);
};


