// source: processed.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.ObjectsInFrameResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api.ObjectsInFrame');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.ObjectsInFrameResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.ObjectsInFrameResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.ObjectsInFrameResponse.displayName = 'proto.api.ObjectsInFrameResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.ObjectsInFrameResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.ObjectsInFrameResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.ObjectsInFrameResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.ObjectsInFrameResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    rawFrameId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    objectInFrame: (f = msg.getObjectInFrame()) && proto.api.ObjectsInFrame.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.ObjectsInFrameResponse}
 */
proto.api.ObjectsInFrameResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.ObjectsInFrameResponse;
  return proto.api.ObjectsInFrameResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.ObjectsInFrameResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.ObjectsInFrameResponse}
 */
proto.api.ObjectsInFrameResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRawFrameId(value);
      break;
    case 2:
      var value = new proto.api.ObjectsInFrame;
      reader.readMessage(value,proto.api.ObjectsInFrame.deserializeBinaryFromReader);
      msg.setObjectInFrame(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.ObjectsInFrameResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.ObjectsInFrameResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.ObjectsInFrameResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.ObjectsInFrameResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRawFrameId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getObjectInFrame();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.api.ObjectsInFrame.serializeBinaryToWriter
    );
  }
};


/**
 * optional string raw_frame_id = 1;
 * @return {string}
 */
proto.api.ObjectsInFrameResponse.prototype.getRawFrameId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.ObjectsInFrameResponse} returns this
 */
proto.api.ObjectsInFrameResponse.prototype.setRawFrameId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ObjectsInFrame object_in_frame = 2;
 * @return {?proto.api.ObjectsInFrame}
 */
proto.api.ObjectsInFrameResponse.prototype.getObjectInFrame = function() {
  return /** @type{?proto.api.ObjectsInFrame} */ (
    jspb.Message.getWrapperField(this, proto.api.ObjectsInFrame, 2));
};


/**
 * @param {?proto.api.ObjectsInFrame|undefined} value
 * @return {!proto.api.ObjectsInFrameResponse} returns this
*/
proto.api.ObjectsInFrameResponse.prototype.setObjectInFrame = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.ObjectsInFrameResponse} returns this
 */
proto.api.ObjectsInFrameResponse.prototype.clearObjectInFrame = function() {
  return this.setObjectInFrame(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.ObjectsInFrameResponse.prototype.hasObjectInFrame = function() {
  return jspb.Message.getField(this, 2) != null;
};


