// source: external.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.Trip');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api.DrivingCondition');
goog.require('proto.api.Event');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.Trip = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.Trip.repeatedFields_, null);
};
goog.inherits(proto.api.Trip, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.Trip.displayName = 'proto.api.Trip';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.Trip.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.Trip.prototype.toObject = function(opt_includeInstance) {
  return proto.api.Trip.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.Trip} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.Trip.toObject = function(includeInstance, msg) {
  var f, obj = {
    startTimeMs: jspb.Message.getFieldWithDefault(msg, 1, 0),
    endTimeMs: jspb.Message.getFieldWithDefault(msg, 2, 0),
    eventList: jspb.Message.toObjectList(msg.getEventList(),
    proto.api.Event.toObject, includeInstance),
    drivingConditionList: jspb.Message.toObjectList(msg.getDrivingConditionList(),
    proto.api.DrivingCondition.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.Trip}
 */
proto.api.Trip.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.Trip;
  return proto.api.Trip.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.Trip} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.Trip}
 */
proto.api.Trip.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStartTimeMs(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEndTimeMs(value);
      break;
    case 3:
      var value = new proto.api.Event;
      reader.readMessage(value,proto.api.Event.deserializeBinaryFromReader);
      msg.addEvent(value);
      break;
    case 4:
      var value = new proto.api.DrivingCondition;
      reader.readMessage(value,proto.api.DrivingCondition.deserializeBinaryFromReader);
      msg.addDrivingCondition(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.Trip.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.Trip.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.Trip} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.Trip.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStartTimeMs();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getEndTimeMs();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getEventList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.api.Event.serializeBinaryToWriter
    );
  }
  f = message.getDrivingConditionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.api.DrivingCondition.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 start_time_ms = 1;
 * @return {number}
 */
proto.api.Trip.prototype.getStartTimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.Trip} returns this
 */
proto.api.Trip.prototype.setStartTimeMs = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 end_time_ms = 2;
 * @return {number}
 */
proto.api.Trip.prototype.getEndTimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.Trip} returns this
 */
proto.api.Trip.prototype.setEndTimeMs = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated Event event = 3;
 * @return {!Array<!proto.api.Event>}
 */
proto.api.Trip.prototype.getEventList = function() {
  return /** @type{!Array<!proto.api.Event>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.Event, 3));
};


/**
 * @param {!Array<!proto.api.Event>} value
 * @return {!proto.api.Trip} returns this
*/
proto.api.Trip.prototype.setEventList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.api.Event=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.Event}
 */
proto.api.Trip.prototype.addEvent = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.api.Event, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.Trip} returns this
 */
proto.api.Trip.prototype.clearEventList = function() {
  return this.setEventList([]);
};


/**
 * repeated DrivingCondition driving_condition = 4;
 * @return {!Array<!proto.api.DrivingCondition>}
 */
proto.api.Trip.prototype.getDrivingConditionList = function() {
  return /** @type{!Array<!proto.api.DrivingCondition>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.DrivingCondition, 4));
};


/**
 * @param {!Array<!proto.api.DrivingCondition>} value
 * @return {!proto.api.Trip} returns this
*/
proto.api.Trip.prototype.setDrivingConditionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.api.DrivingCondition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.DrivingCondition}
 */
proto.api.Trip.prototype.addDrivingCondition = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.api.DrivingCondition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.Trip} returns this
 */
proto.api.Trip.prototype.clearDrivingConditionList = function() {
  return this.setDrivingConditionList([]);
};


