# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: external.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='external.proto',
  package='api',
  syntax='proto3',
  serialized_options=b'Z\010api/type',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x65xternal.proto\x12\x03\x61pi\x1a\x0c\x63ommon.proto\"\x7f\n\x04Trip\x12\x15\n\rstart_time_ms\x18\x01 \x01(\x03\x12\x13\n\x0b\x65nd_time_ms\x18\x02 \x01(\x03\x12\x19\n\x05\x65vent\x18\x03 \x03(\x0b\x32\n.api.Event\x12\x30\n\x11\x64riving_condition\x18\x04 \x03(\x0b\x32\x15.api.DrivingCondition\"|\n\x10\x44rivingCondition\x12*\n\x0e\x63ondition_type\x18\x02 \x03(\x0e\x32\x12.api.ConditionType\x12\x10\n\x08severity\x18\x05 \x03(\x01\x12\x15\n\rstart_time_ms\x18\x06 \x01(\x03\x12\x13\n\x0b\x65nd_time_ms\x18\x07 \x01(\x03\"b\n\x05\x45vent\x12\"\n\nevent_type\x18\x03 \x01(\x0e\x32\x0e.api.EventType\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x10\n\x08severity\x18\x05 \x01(\x01\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\"N\n\x0fTripListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\rstart_time_ms\x18\x02 \x01(\x03\x12\x13\n\x0b\x65nd_time_ms\x18\x03 \x01(\x03\"Y\n\x10TripListResponse\x12\x1b\n\x06header\x18\x01 \x01(\x0b\x32\x0b.api.Header\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x17\n\x04trip\x18\x03 \x03(\x0b\x32\t.api.TripB\nZ\x08\x61pi/typeb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_TRIP = _descriptor.Descriptor(
  name='Trip',
  full_name='api.Trip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time_ms', full_name='api.Trip.start_time_ms', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time_ms', full_name='api.Trip.end_time_ms', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event', full_name='api.Trip.event', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='driving_condition', full_name='api.Trip.driving_condition', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=164,
)


_DRIVINGCONDITION = _descriptor.Descriptor(
  name='DrivingCondition',
  full_name='api.DrivingCondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='condition_type', full_name='api.DrivingCondition.condition_type', index=0,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='severity', full_name='api.DrivingCondition.severity', index=1,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time_ms', full_name='api.DrivingCondition.start_time_ms', index=2,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time_ms', full_name='api.DrivingCondition.end_time_ms', index=3,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=290,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='api.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_type', full_name='api.Event.event_type', index=0,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Event.value', index=1,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='severity', full_name='api.Event.severity', index=2,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_ms', full_name='api.Event.timestamp_ms', index=3,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=390,
)


_TRIPLISTREQUEST = _descriptor.Descriptor(
  name='TripListRequest',
  full_name='api.TripListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='api.TripListRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time_ms', full_name='api.TripListRequest.start_time_ms', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time_ms', full_name='api.TripListRequest.end_time_ms', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=470,
)


_TRIPLISTRESPONSE = _descriptor.Descriptor(
  name='TripListResponse',
  full_name='api.TripListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='api.TripListResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='api.TripListResponse.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trip', full_name='api.TripListResponse.trip', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=561,
)

_TRIP.fields_by_name['event'].message_type = _EVENT
_TRIP.fields_by_name['driving_condition'].message_type = _DRIVINGCONDITION
_DRIVINGCONDITION.fields_by_name['condition_type'].enum_type = common__pb2._CONDITIONTYPE
_EVENT.fields_by_name['event_type'].enum_type = common__pb2._EVENTTYPE
_TRIPLISTRESPONSE.fields_by_name['header'].message_type = common__pb2._HEADER
_TRIPLISTRESPONSE.fields_by_name['trip'].message_type = _TRIP
DESCRIPTOR.message_types_by_name['Trip'] = _TRIP
DESCRIPTOR.message_types_by_name['DrivingCondition'] = _DRIVINGCONDITION
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['TripListRequest'] = _TRIPLISTREQUEST
DESCRIPTOR.message_types_by_name['TripListResponse'] = _TRIPLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Trip = _reflection.GeneratedProtocolMessageType('Trip', (_message.Message,), {
  'DESCRIPTOR' : _TRIP,
  '__module__' : 'external_pb2'
  # @@protoc_insertion_point(class_scope:api.Trip)
  })
_sym_db.RegisterMessage(Trip)

DrivingCondition = _reflection.GeneratedProtocolMessageType('DrivingCondition', (_message.Message,), {
  'DESCRIPTOR' : _DRIVINGCONDITION,
  '__module__' : 'external_pb2'
  # @@protoc_insertion_point(class_scope:api.DrivingCondition)
  })
_sym_db.RegisterMessage(DrivingCondition)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'external_pb2'
  # @@protoc_insertion_point(class_scope:api.Event)
  })
_sym_db.RegisterMessage(Event)

TripListRequest = _reflection.GeneratedProtocolMessageType('TripListRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRIPLISTREQUEST,
  '__module__' : 'external_pb2'
  # @@protoc_insertion_point(class_scope:api.TripListRequest)
  })
_sym_db.RegisterMessage(TripListRequest)

TripListResponse = _reflection.GeneratedProtocolMessageType('TripListResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRIPLISTRESPONSE,
  '__module__' : 'external_pb2'
  # @@protoc_insertion_point(class_scope:api.TripListResponse)
  })
_sym_db.RegisterMessage(TripListResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
