name: generate-protobuf
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2

      - name: Install protoc-gen-go
        run: go get -u google.golang.org/protobuf/cmd/protoc-gen-go

      - name: Protoc go
        run: protoc ./api/type/*.proto --go_out=./proto_out/go/ -I=./api/type 

      - name: Protoc python
        # note the find and replace.  its a very hackey solution.
        run: protoc ./api/type/*.proto --python_out=./proto_out/python -I=./api/type 

      - name: write generated code
        if: github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v7
        with:
          add: 'proto_out'
          message: 'auto generated commit to write proto_out'
