name: generate-protobuf
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2

      - name: Install protoc-gen-go
        run: go get -u google.golang.org/protobuf/cmd/protoc-gen-go

      - name: Protoco go
        run: protoc ./api/type/*.proto --go_out=../ -I=./api/type 

      - name: stage generated code
        if: github.ref == 'refs/heads/main'
        run: git add .

      - name: commit generate code
        if: github.ref == 'refs/heads/main'
        run: git commit -m "update generated code"

      - name: fetch from main
        if: github.ref == 'refs/heads/main'
        run: git fetch origin main

      - name: push code to main
        if: github.ref == 'refs/heads/main'
        run: git push origin HEAD:main

      