name: generate-protobuf
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_TOKEN_LUCA }}
          persist-credentials: true

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2

      - name: Install protoc-gen-go
        run: go get -u google.golang.org/protobuf/cmd/protoc-gen-go

      - name: Protoc go
        run: protoc ./api/type/*.proto --go_out=./proto_out/go/ -I=./api/type 

      - name: Protoc python
        run: protoc ./api/type/*.proto --python_out=./proto_out/python/api/type -I=./api/type
        
        # TODO(lucaloncar): figure out how to protoc python properly
      - name: Hack path with find and replace
        run: find ./proto_out/python/api/type/*_pb2.py -type f -exec sed -i '' "s/^import \(.*\) as/from . import \1 as/g" {} \;

      - name: Write generated code
        if: github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v7
        with:
          add: 'proto_out --force'
          message: 'auto generated commit to write proto_out'
